

services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    ports:
      - "5173:5173" 
    networks:
      - appnet

  backend:
    image: php:8.2-apache
    container_name: php-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8060:80"   
    depends_on:
      - db
    networks:
      - appnet
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydatabase
    command: >
      bash -c "docker-php-ext-install mysqli pdo_mysql && apache2-foreground"


  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306" 
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8061:80"   
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet: